/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "tertiary-container": "#a65900",
        "on-background": "#0b1c30",
        "on-tertiary": "#ffffff",
        "primary-fixed-dim": "#b4c5ff",
        "on-tertiary-container": "#ffede1",
        "secondary": "#006a61",
        "surface-tint": "#0053db",
        "error-container": "#ffdad6",
        "surface-container-low": "#eff4ff",
        "inverse-primary": "#b4c5ff",
        "on-primary-fixed": "#00174b",
        "on-surface": "#0b1c30",
        "secondary-fixed-dim": "#6bd8cb",
        "surface-container-highest": "#d3e4fe",
        "on-primary-container": "#eeefff",
        "on-tertiary-fixed": "#2f1500",
        "tertiary-fixed-dim": "#ffb77d",
        "secondary-fixed": "#89f5e7",
        "inverse-on-surface": "#eaf1ff",
        "on-primary": "#ffffff",
        "secondary-container": "#86f2e4",
        "outline-variant": "#c3c6d7",
        "on-secondary-fixed-variant": "#005049",
        "on-error": "#ffffff",
        "background": "#f8f9ff",
        "error": "#ba1a1a",
        "surface-variant": "#d3e4fe",
        "tertiary-fixed": "#ffdcc3",
        "on-surface-variant": "#434655",
        "surface-dim": "#cbdbf5",
        "inverse-surface": "#213145",
        "tertiary": "#824500",
        "on-secondary-fixed": "#00201d",
        "on-error-container": "#93000a",
        "primary-container": "#2563eb",
        "surface-container": "#e5eeff",
        "on-secondary": "#ffffff",
        "primary-fixed": "#dbe1ff",
        "on-tertiary-fixed-variant": "#6e3900",
        "surface-container-high": "#dce9ff",
        "surface-bright": "#f8f9ff",
        "surface": "#f8f9ff",
        "surface-container-lowest": "#ffffff",
        "primary": "#004ac6",
        "on-primary-fixed-variant": "#003ea8",
        "on-secondary-container": "#006f66",
        "outline": "#737686"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "spacing": {
        "lg": "40px",
        "gutter": "24px",
        "xs": "8px",
        "xl": "64px",
        "sm": "16px",
        "base": "4px",
        "md": "24px",
        "margin": "32px"
      },
      "fontFamily": {
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "code-sm": ["monospace"],
        "headline-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"]
      },
      "fontSize": {
        "body-lg": ["16px", {"lineHeight": "24px", "letterSpacing": "0", "fontWeight": "400"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "600"}],
        "body-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0", "fontWeight": "400"}],
        "headline-sm": ["20px", {"lineHeight": "28px", "letterSpacing": "0", "fontWeight": "600"}],
        "code-sm": ["12px", {"lineHeight": "18px", "letterSpacing": "0", "fontWeight": "400"}],
        "headline-md": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "500"}]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
